<?php
/* @var $this Tmm_billsController */
/* @var $model Bills */
$this->breadcrumbs=array(
	'账单详情管理页'=>array('/admin/tmm_cash/admin'),
	$model->order_no,
);
?>

<h1>查看 账单详情 <font color='#eb6100'><?php echo $model->order_no; ?></font></h1>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		array(
				'name'=>'id',
		),
		array(
				'name'=>'order_id',
		),
		array(
				'name'=>'order_no',
		),
		array(
				'name'=>'order_items_id',
		),
		array(
				'name'=>'group_no',
		),
		array(
				'name'=>'organizer_id',
		),
		array(
				'name'=>'order_organizer_id',
		),
		array(
				'name'=>'user_id',
		),
		array(
				'name'=>'order_shops_id',
		),
		array(
				'name'=>'shops_name',
		),
		array(
				'name'=>'agent_id',
		),
		array(
				'name'=>'store_id',
		),
		array(
				'name'=>'manager_id',
		),
		array(
				'name'=>'shops_id',
		),
		array(
				'name'=>'shops_c_id',
		),
		array(
				'name'=>'shops_c_name',
		),
		array(
				'name'=>'items_id',
		),
		array(
				'name'=>'items_c_id',
		),
		array(
				'name'=>'items_c_name',
		),
		array(
				'name'=>'items_name',
		),
		array(
				'name'=>'group_price',
		),
		array(
				'name'=>'user_order_count',
		),
		array(
				'name'=>'user_pay_count',
		),
		array(
				'name'=>'user_submit_count',
		),
		array(
				'name'=>'user_price',
		),
		array(
				'name'=>'user_go_count',
		),
		array(
				'name'=>'user_price_count',
		),
		array(
				'name'=>'items_push',
		),
		array(
				'name'=>'items_push_orgainzer',
		),
		array(
				'name'=>'items_push_store',
		),
		array(
				'name'=>'items_push_agent',
		),
		array(
				'name'=>'items_money',
		),
		array(
				'name'=>'items_money_orgainzer',
		),
		array(
				'name'=>'items_money_store',
		),
		array(
				'name'=>'items_money_agent',
		),
		array(
				'name'=>'price',
		),
		array(
				'name'=>'number',
		),
		array(
				'name'=>'total',
		),
		array(
				'name'=>'cash_id',
		),
		array(
				'name'=>'cash_status',
				'value'=>$model::$_cash_status[$model->cash_status],
		),
		array(
				'name'=>'add_time',
				'type'=>'datetime',
		),
		array(
				'name'=>'up_time',
				'type'=>'datetime',
		),
		array(
				'name'=>'son_status',
				'value'=>$model::$_son_status[$model->son_status],
		),
		array(
				'name'=>'status',
				'value'=>$model::$_status[$model->status],
		),
	),
)); ?>