<?php
/* @var $this Tmm_agentController */
/* @var $model Agent */

$this->breadcrumbs=array(
	'运营商管理页'=>array('admin'),
	$model->phone,
);
?>

<h1>查看 运营商详情 <font color='#eb6100'><?php echo $model->phone; ?></font></h1>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		array(
				'name'=>'id',
		),
		array(
				'name'=>'admin_id',
				'value'=>$model->Agent_Admin->username."[".$model->Agent_Admin->name."]",
		),
		array(
				'name'=>'phone',
		),
		array(
				'name'=>'merchant_count',
		),
		array(
				'name'=>'firm_name',
		),
		array(
			'name'=>'firm_tel',
		),
		array(
			'name'=>'firm_postcode',
		),
		array(
				'name'=>'area_id_p',
				'value'=>$model->Agent_area_id_p_Area_id->name
		),
		array(
				'name'=>'area_id_m',
				'value'=>$model->Agent_area_id_m_Area_id->name
		),
		array(
				'name'=>'area_id_c',
				'value'=>$model->Agent_area_id_c_Area_id->name
		),
		array(
				'name'=>'address',
		),
		array(
				'name'=>'area_select',
				'type'=>'raw',
				'value'=>Area::view_all_area(Area::all_area(array(),$model->id)),
		),
		array(
			'name'=>'com_contacts',
		),
		array(
			'name'=>'com_identity',
		),
		array(
			'name'=>'com_phone',
		),
		array(
				'name'=>'bl_code',
		),
		array(
				'name'=>'bl_img',
				'type'=>'raw',
				'value'=>$this->show_img($model->bl_img),
		),
		array(
				'name'=>'manage_name',
		),
		array(
				'name'=>'manage_phone',
		),
		array(
			'name'=>'manage_identity',
		),
		array(
				'name'=>'identity_before',
				'type'=>'raw',
				'value'=>$this->show_img($model->identity_before),
		),
		array(
				'name'=>'identity_after',
				'type'=>'raw',
				'value'=>$this->show_img($model->identity_after),
		),
		array(
			'name'=>'identity_hand',
			'type'=>'raw',
			'value'=>$this->show_img($model->identity_hand),
		),
		array(
				'name'=>'Agent_Bank.name',
		),
		array(
				'name'=>'bank_branch',
		),
		array(
				'name'=>'bank_name',
		),
		array(
				'name'=>'bank_code',
		),
		array(
				'name'=>'deposit',
		),
		array(
				'name'=>'income_count',
		),
		array(
				'name'=>'cash',
		),
		array(
				'name'=>'money',
		),
		array(
				'name'=>'count',
		),
		array(
				'name'=>'login_error',
		),
		array(
				'name'=>'error_count',
		),
		array(
				'name'=>'login_time',
				'type'=>'datetime',
		),
		array(
				'name'=>'login_ip',
		),
		array(
				'name'=>'last_time',
				'type'=>'datetime',
		),
		array(
				'name'=>'last_ip',
		),
		array(
				'name'=>'add_time',
				'type'=>'datetime',
		),
		array(
				'name'=>'up_time',
				'type'=>'datetime',
		),
		array(
				'name'=>'status',
				'value'=>$model::$_status[$model->status],
		),
		array(
			'label'=>'银行卡',
			'type'=>'raw',
			'value'=>CHtml::link('点击查看我的银行卡',Yii::app()->createUrl("admin/Tmm_bankCard/admin",array("card_id"=>$model->phone,"card_type"=>BankCard::agent)),array('color'=>'red')),
		),
	),
)); ?>