<?php
/* @var $this Tmm_accountLogController */
/* @var $model AccountLog */

$this->breadcrumbs=array(
	'资金流水管理页'=>array('admin'),
	$model->funds_type_name,
);
?>

<h1>查看 资金流水 <font color='#eb6100'><?php echo CHtml::encode($model->funds_type_name); ?></font></h1>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		array(
			'name'=>'id',
		),
		array(
			'name'=>'account_no',
		),
		array(
			'name'=>'account_type',
			'value'=>$model::$_account_type[$model->account_type],
		),
		array(
			'name'=>'account_id',
			'value'=>$model::getRoleName($model,$model->account_type),
		),
		array(
			'name'=>'to_account_type',
			'value'=>$model::$_to_account_type[$model->to_account_type],
		),
		array(
			'name'=>'to_account_id',
			'value'=>$model::getRoleName($model,$model->to_account_type,'to'),
		),
		array(
			'name'=>'manage_account_type',
			'value'=>$model::$_manage_account_type[$model->manage_account_type],
		),
		array(
			'name'=>'manage_account_id',
			'value'=>$model::getRoleName($model,$model->manage_account_type,'manage'),
		),
		array(
			'name'=>'funds_type',
		),
		array(
			'name'=>'funds_type_name',
		),
		array(
				'name'=>'use_money',
		),
		array(
			'name'=>'money_type',
			'value'=>$model::$_money_type[$model->money_type],
		),
		array(
			'name'=>'count',
		),
		array(
			'name'=>'total',
		),
		array(
			'name'=>'money',
		),
		array(
			'name'=>'no_money',
		),
		array(
			'name'=>'cash_count',
		),
		array(
			'name'=>'pay_count',
		),
		array(
			'name'=>'refund_count',
		),
		array(
			'name'=>'consume_count',
		),
		array(
			'name'=>'not_consume_count',
		),
		array(
			'name'=>'after_count',
		),
		array(
			'name'=>'after_total',
		),
		array(
			'name'=>'after_money',
		),
		array(
			'name'=>'after_no_money',
		),
		array(
			'name'=>'after_cash_count',
		),
		array(
			'name'=>'after_pay_count',
		),
		array(
			'name'=>'after_refund_count',
		),
		array(
			'name'=>'after_consume_count',
		),
		array(
			'name'=>'after_not_consume_count',
		),
		array(
			'name'=>'info_type',
			'value'=>$model::$_info_type[$model->info_type],
		),
		array(
			'name'=>'info_id',
			'value'=>$model::getInfoName($model,$model->info_type),
		),
		array(
			'name'=>'info',
			'type'=>'raw',
		),
		array(
			'name'=>'name',
		),
		array(
			'name'=>'ip',
		),
		array(
			'name'=>'address',
		),
		array(
			'name'=>'add_time',
			'type'=>'datetime',
		),
		array(
			'name'=>'up_time',
			'type'=>'datetime',
		),
		array(
			'name'=>'up_count',
		),
		array(
			'name'=>'log_status',
			'value'=>$model::$_log_status[$model->log_status],
		),
		array(
			'name'=>'centre_status',
			'value'=>$model::$_centre_status[$model->centre_status],
		),
		array(
			'name'=>'status',
			'value'=>$model::$_status[$model->status],
		),
	),
)); 
?>

