<?php 
 return array(
	'admin@Tmm_adminOwn',
	'admin@Tmm_adminPwd',
	'admin@Tmm_adminModify',
	'admin@Tmm_errorIndex',
	'admin@Tmm_loginIndex',
 	'admin@Tmm_loginOut',
 	'admin@Tmm_loginCaptcha',	
 	'admin@Tmm_softwareQuery',
 	'admin@Tmm_softwareDownload',
 	'admin@Tmm_qrcodeUser',
  	'admin@Tmm_qrcodeStore',
 	'admin@Tmm_qrcodePad',
 	'admin@Tmm_hotelUploads',
 	'admin@Tmm_eatUploads',
 	'admin@Tmm_playUploads',		
 	'admin@Tmm_homeIndex',
 	'admin@Tmm_homeTop',
 	'admin@Tmm_homeLeft',
);
?>