<?php 
 return array(
	'admin@Tmm_adminOwn',
	'admin@Tmm_adminPwd',
	'admin@Tmm_adminModify',
	'admin@Tmm_eatUploads',
	'admin@Tmm_errorIndex',
	'admin@Tmm_homeIndex',
	'admin@Tmm_homeTop',
	'admin@Tmm_homeLeft',
	'admin@Tmm_hotelUploads',
	'admin@Tmm_loginCaptcha',
	'admin@Tmm_loginIndex',
	'admin@Tmm_loginOut',
	'admin@Tmm_playUploads',
	'admin@Tmm_qrcodeUser',
	'admin@Tmm_qrcodeStore',
	'admin@Tmm_qrcodePad',
	'admin@Tmm_softwareQuery',
	'admin@Tmm_softwareDownload'
);
?>