<?php
$this->widget('zii.widgets.CDetailView', array(
    'data'=>$model,
    'attributes'=>array(
        array(
            'name'=>'id',
        ),
        array(
            'name'=>'cash_type',
            'value'=>$model::$_cash_type[$model->cash_type],
        ),
        array(
            'name'=>'cash_id',
        	'value'=>$model::getRoleName($model, $model->cash_type),
        ),
        array(
            'name'=>'admin_id_first',
            'value'=>isset($model->CashFirst_Admin->name) ?$model->CashFirst_Admin->name:"--"
        ),
        array(
            'name'=>'remark_first',
        ),
        array(
            'name'=>'first_time',
        	'value'=>$model->first_time==0?"--":Yii::app()->format->FormatDate($model->first_time)       		
        ),
        array(
            'name'=>'admin_id_double',
            'value'=>isset($model->CashDouble_Admin->name) ?$model->CashDouble_Admin->name:"-"
        ),
        array(
            'name'=>'remark_double',
        ),
        array(
            'name'=>'double_time',
            'value'=>$model->double_time==0?"--":Yii::app()->format->FormatDate($model->double_time) 
        ),
        array(
            'name'=>'admin_id_submit',
            'value'=>isset($model->CashSubmit_Admin->name) ?$model->CashSubmit_Admin->name:"-"
        ),
        array(
            'name'=>'remark_submit',
        ),
        array(
            'name'=>'submit_time',
        	'value'=>$model->submit_time==0?"--":Yii::app()->format->FormatDate($model->submit_time)
        ),
        array(
            'name'=>'money',
        ),
        array(
            'name'=>'price',
        ),
        array(
            'name'=>'fee_price',
        ),
        array(
            'name'=>'fact_price',
        ),
        array(
            'name'=>'bank_card_id',
        	'type'=>'raw',
        	'value'=>CHtml::link($model::getRoleName($model, $model->cash_type),array('/admin/tmm_bankCard/view','id'=>$model->bank_card_id)),
        ),
        array(
            'name'=>'bank_id',
        	'value'=>$model->Cash_Bank->name,
        ),
        array(
            'name'=>'bank_name',
        ),
        array(
            'name'=>'bank_branch',
        ),
        array(
            'name'=>'bank_code',
        ),
        array(
            'name'=>'bank_type',
        ),
        array(
            'name'=>'bank_identity',
        ),
        array(
            'name'=>'cash_status',
            'value'=>$model::$_cash_status[$model->cash_status],
        ),
        array(
            'name'=>'audit_status',
            'value'=>$model::$_audit_status[$model->audit_status],
        ),
//         array(
//             'name'=>'pay_type',
//             'value'=>$model::$_pay_type[$model->pay_type],
//         ),
        array(
            'name'=>'pay_time',
            'value'=>$model->pay_time==0?"--":Yii::app()->format->FormatDate($model->pay_time)
        ),
        array(
            'name'=>'add_time',
            'type'=>'datetime',
        ),
        array(
            'name'=>'up_time',
            'type'=>'datetime',
        ),
        array(
            'name'=>'status',
            'value'=>$model::$_status[$model->status],
        ),
    ),
));
?>