<?php
/* @var $this Tmm_storeController */
/* @var $model StoreUser */

$this->breadcrumbs=array(
	'供应商账号管理页'=>array('admin'),
	$model->phone,
);
?>

<h1>查看 供应商账号管理页 <font color='#eb6100'><?php echo CHtml::encode($model->phone); ?></font>信息</h1>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		array(
				'name'=>'id',
		),
		array(
				'name'=>'phone',
		),
		array(
				'name'=>'agent_id',
				'value'=>$model->Store_Agent->phone,
		),
		array(
				'name'=>'Store_Content.name',
		),
		array(
				'name'=>'Store_Content.income_count',
		),
		array(
				'name'=>'Store_Content.cash',
		),
		array(
				'name'=>'Store_Content.money',
		),
		array(
				'name'=>'Store_Content.deposit',
		),
		array(
			'name'=>'Store_Content.area_id_p',
			'value'=>$model->Store_Content->Content_area_id_p_Area_id->name,
		),
		array(
			'name'=>'Store_Content.area_id_m',
			'value'=>$model->Store_Content->Content_area_id_m_Area_id->name,
		),
		array(
			'name'=>'Store_Content.area_id_c',
			'value'=>$model->Store_Content->Content_area_id_c_Area_id->name,
		),
		array(
				'name'=>'Store_Content.address',
		),
		array(
				'name'=>'Store_Content.store_tel',
		),
		array(
				'name'=>'Store_Content.store_postcode',
		),
		array(
				'name'=>'Store_Content.lx_contacts',
		),
		array(
				'name'=>'Store_Content.lx_identity_code',
		),
		array(
				'name'=>'Store_Content.lx_phone',
		),
		array(
				'name'=>'Store_Content.identity_before',
				'type'=>'raw',
				'value'=>$this->show_img($model->Store_Content->identity_before),
		),
		array(
				'name'=>'Store_Content.identity_after',
				'type'=>'raw',
				'value'=>$this->show_img($model->Store_Content->identity_after),
		),
		array(
				'name'=>'Store_Content.identity_hand',
				'type'=>'raw',
				'value'=>$this->show_img($model->Store_Content->identity_hand),
		),
		array(
				'name'=>'Store_Content.com_contacts',
		),
		array(
				'name'=>'Store_Content.com_phone',
		),
		array(
				'name'=>'Store_Content.com_identity',
		),
		array(
				'name'=>'Store_Content.bl_code',
		),
		array(
				'name'=>'Store_Content.bl_img',
				'type'=>'raw',
				'value'=>$this->show_img($model->Store_Content->bl_img),
		),
		array(
			'name'=>'select_tags',
			'type'=>'raw',
			'value'=>TagsElement::show_tags($model->Store_TagsElement),
		),
		array(
				'name'=>'Store_Content.bank_id',
				'value'=>isset($model->Store_Content->Content_Bank->name)?$model->Store_Content->Content_Bank->name:'',
		),
		array(
				'name'=>'Store_Content.bank_name',
		),
		array(
				'name'=>'Store_Content.bank_branch',
		),
		array(
				'name'=>'Store_Content.bank_code',
		),
		array(
				'name'=>'Store_Content.son_count',
		),
		array(
				'name'=>'Store_Content.son_limit',
		),
		array(
				'name'=>'Store_Content.up_time',
				'type'=>'datetime',
		),
		array(
				'name'=>'Store_Content.pass_time',
				'type'=>'datetime',
		),
		array(
				'name'=>'Store_Content.add_time',
				'type'=>'datetime',
		),
		array(
			'name'=>'last_time',
		),
		array(
			'name'=>'login_error',
		),
		array(
			'name'=>'error_count',
		),
		array(
			'name'=>'login_ip',
		),
		array(
			'name'=>'login_time',
			'type'=>'datetime',
		),
		array(
			'name'=>'login_address',
		),
		array(
			'name'=>'last_ip',
		),
		array(
			'name'=>'last_time',
			'type'=>'datetime',
		),
		array(
			'name'=>'last_address',
		),
		array(
			'name'=>'add_time',
			'type'=>'datetime',
		),
		array(
			'name'=>'up_time',
			'type'=>'datetime',
		),
		array(
			'name'=>'out_time',
			'type'=>'datetime',
		),
		array(
			'name'=>'status',
			'value'=>$model::$_status[$model->status],
		),
		array(
			'label'=>'银行卡',
			'type'=>'raw',
			'value'=>CHtml::link('点击查看我的银行卡',Yii::app()->createUrl("admin/Tmm_bankCard/admin",array("card_id"=>$model->phone,"card_type"=>BankCard::store)),array('color'=>'red')),
		),
	),
)); ?>