
--
-- 表的结构 `tmm_order`
--
DROP TABLE IF EXISTS `tmm_order`;
CREATE TABLE IF NOT EXISTS `tmm_order` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `order_organizer_id` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '归属组织者总订单表',
  `son_order_count` decimal(13,2) NOT NULL DEFAULT '0.00' COMMENT '子订单总费用',
  `order_no` varchar(128) NOT NULL COMMENT '订单号',
  `order_type` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '订单类型 0未知 1 点（多个点组合） 2 线 3 结伴游',
  `user_id` int(11) unsigned NOT NULL COMMENT ' 用户ID',
  `order_price` decimal(13,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '订单总价',
  `pay_price` decimal(13,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '支付回调总价',
  `price` decimal(13,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '实际支付总价',
  `trade_no` varchar(255) DEFAULT '' COMMENT '支付回调',
  `trade_name` varchar(128) DEFAULT '' COMMENT '支付账号',
  `service_price` decimal(13,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '第三方支付服务费',
  `service_fee` float(5,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '第三方支付服务费率%',
  `pay_type` tinyint(3) unsigned NOT NULL DEFAULT '1' COMMENT '支付类型1=支付宝2=微信...',
  `user_go_count` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '用户出游人数量',
  `user_price` decimal(13,2) NOT NULL DEFAULT '0.00' COMMENT '服务费用/人',
  `user_price_fact` decimal(13,2) NOT NULL DEFAULT '0.00' COMMENT '实际服务费用/人',
  `pay_time` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '支付成功时间',
  `status_go` tinyint(3) NOT NULL DEFAULT '0' COMMENT '记录状态0没选择 1去 -1不去',
  `go_time` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '出游时间',
  `past_time` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '过期时间',
  `sale_status` tinyint(3) NOT NULL DEFAULT 0 COMMENT '售后状态',
  `consume_status` tinyint(3) NOT NULL DEFAULT 0 COMMENT '消费状态',
  `add_time` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '创建时间',
  `up_time` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '更新时间',
  `pay_status` tinyint(3) NOT NULL DEFAULT '0' COMMENT '支付状态1=已支付0=未支付2=已过期',
  `order_status` tinyint(3) NOT NULL DEFAULT '0' COMMENT '订单状态1=已支付0=未支付2=已退款....',
  `centre_status` tinyint(3) NOT NULL DEFAULT '0' COMMENT '状态',
  `status` tinyint(3) NOT NULL DEFAULT '1' COMMENT '记录状态0禁用1正常-1删除',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='订单主表 ' AUTO_INCREMENT=1;




DROP TABLE IF EXISTS `tmm_order_items`;
CREATE TABLE IF NOT EXISTS `tmm_order_items` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `order_items_id` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '归属活动项目id 默认为零表示 （可能是自助游 或者是活动总定订单）',
  `organizer_id` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '归属组织者表',
  `order_organizer_id` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '归属组织者订单详情表',
  `user_id` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '归属用户',
  `order_id` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '归属订单表',
  `order_shops_id` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '归属订单商品表（复制表）',
  `store_id` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '项目归属商家',
  `manager_id` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '商家管理者',
  `agent_id` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '项目归属代理商',
  `shops_id` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '商品来源',
  `shops_name` varchar(128) NOT NULL DEFAULT '' COMMENT '商品名称',
  `shops_c_id` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '归属商品分类',
  `shops_c_name` varchar(20) NOT NULL DEFAULT '0' COMMENT '归属商品分类名称',
  `items_id` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '项目来源',
  `items_c_id` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '归属项目分类',
  `items_c_name` varchar(20) NOT NULL DEFAULT '0' COMMENT '归属项目分类名称',
  `items_name` varchar(128) NOT NULL DEFAULT '0' COMMENT '项目名称',
  `items_address` varchar(200) NOT NULL DEFAULT '0' COMMENT '项目地址',
  `items_push` float(5,2) NOT NULL DEFAULT '0.00' COMMENT '平台对项目的抽成 %(生效值)',
  `items_push_orgainzer` float(5,2) NOT NULL DEFAULT '0.00' COMMENT '组织者对项目的抽成 %(生效值)',
  `items_push_store` float(5,2) NOT NULL DEFAULT '0.00' COMMENT '商家对项目的抽成 %(生效值)',
  `items_push_agent` float(5,2) NOT NULL DEFAULT '0.00' COMMENT '代理商平台对项目的抽成 %(生效值)',
  `items_map` varchar(100) DEFAULT '' COMMENT '地图',
  `items_phone` varchar(20) DEFAULT '' COMMENT '联系电话',
  `items_weixin` varchar(20) DEFAULT '' COMMENT '微信号',
  `items_content` text NOT NULL COMMENT '项目详细内容',
  `items_lng` decimal(10,6) NOT NULL DEFAULT '0.000000' COMMENT '经度',
  `items_lat` decimal(10,6) NOT NULL DEFAULT '0.000000' COMMENT '纬度',
  `items_free_status` TINYINT(3) NOT NULL DEFAULT 1 COMMENT '0免费 1不免费', 
  `items_img` varchar(100) DEFAULT '' COMMENT '随机一张图片',
  `items_start_work` time NOT NULL DEFAULT '00:00:00' COMMENT '工作开始时间',
  `items_end_work` time NOT NULL DEFAULT '23:59:59' COMMENT '工作结束时间',
  `items_up_time` int(10) unsigned NOT NULL COMMENT '最后一次更新时间',
  `items_pub_time` int(10) unsigned NOT NULL COMMENT '项目审核通过时间',
  `shops_sort` tinyint(3) unsigned NOT NULL DEFAULT '50' COMMENT '点排序',
  `shops_day_sort` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '区分天单位(半天)',
  `shops_half_sort` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '线 结伴游 排序',
  `shops_dot_id` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '当前项目关联点id',
  `shops_thrand_id` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '当前项目关联线id',
  `shops_info` text NOT NULL COMMENT '项目简介',
  `shops_up_time` int(10) unsigned NOT NULL COMMENT '最后一次更新时间',
  `shops_pub_time` int(10) NOT NULL COMMENT '商品审核通过时间',
  `total` decimal(13,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '总计总额',
  `employ_time` int(10) unsigned NOT NULL COMMENT '消费时间',
  `barcode` varchar(100) NOT NULL DEFAULT '' COMMENT '消费码',
  `is_shops` tinyint(3) NOT NULL DEFAULT '0' COMMENT '商家同意是否接单 0没选择 1同意 -1 不同意',
  `is_barcode` tinyint(3) NOT NULL DEFAULT '0' COMMENT '-1 无效 0 可消费 1已消费',
  `sale_status` tinyint(3) NOT NULL DEFAULT 0 COMMENT '售后状态',
  `scan_barcode` varchar(100) NOT NULL DEFAULT '' COMMENT '扫码',
  `add_time` int(10) unsigned NOT NULL COMMENT '创建时间',
  `up_time` int(10) unsigned NOT NULL COMMENT '更新时间',
  `status` tinyint(3) NOT NULL DEFAULT '1' COMMENT '记录状态1正常0禁用-1删除',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='订单项目详细情况' AUTO_INCREMENT=1 ;